services:
  redis:
    image: "redis:7.4.2-alpine"
    hostname: redis
    ports:
      - "16379:6379"

  postgres:
    image: "postgres:17.4-alpine3.21"
    hostname: db
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 3s
      timeout: 3s
      retries: 10
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432